Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/07/2019
Var
a, b :inteiro
resultado:logico

Inicio
a <-6
b <- 2
resultado <- a <> b
 escreval("teste com operador diferente a: ", a,"<>",b ,"?", resultado)


Fimalgoritmo