Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/07/2019
Var

       n: inteiro

Inicio
     escreval("digite a nota do aluno")
      leia (n)
      se (n>=0) e (n<=10) entao
     escreval("nota  invalida,por favor digite novamente")
      senao
     escreval(" nota", n)
      fimse

Fimalgoritmo